trigger:
  branches:
    include:
    - feature/*
    - master
variables:
- name: projectName
  value: test
pool: ec2-agents
stages:
  - stage: ServiceBuild
    condition:  startsWith(variables['build.sourceBranch'], 'refs/heads/feature/')
    displayName: Build Service
    jobs:
    - job: BuildImage
      displayName: Build Image
      steps:
      - task: Docker@2
        displayName: buildImage
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'mohamedhani/$(projectName)'
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        displayName:  Push Image
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'mohamedhani/$(projectName)'
          command: 'push'
      


