trigger:
  branches:
    include:
    - feature/*
    - master
variables:
- name: projectName
  value: test
pool: ec2-agents
stages:
  - stage: ServiceBuild
    condition:  startsWith(variables['build.sourceBranch'], 'refs/heads/feature/')
    displayName: Build Service
    jobs:

    - job: BuildImage
      displayName: Build Image
      container:
        image: "gcr.io/kaniko-project/executor:debug"
        options: --entrypoint "/busybox/sleep"  9999
      steps:
      - script: |
          #!/busybox/sh
          /kaniko/executor --dockerfile  $(Pipeline.Workspace)/Dockerfile  --context  $(Pipeline.Workspace)/ --destination mohamedhani/$(projectName)
      


